In [410]:
import os
import pandas as pd


cols = ["Destination", "Prices", "Departure date", "Arrival date", "Airline"]
path = os.path.join(os.getcwd(), "letovi.csv")
data = pd.read_csv(path, names=cols, skiprows=1)

data.rename_axis()
data

,Destination,Prices,Departure date,Arrival date,Airline
0,Valletta,180 kn,Sat 4 Dec,Sat 4 Dec,Ryanair
1,Paphos,211 kn,Sat 4 Dec,Mon 6 Dec,Ryanair
2,Tallinn,300 kn,Sat 4 Dec,Sun 12 Dec,Ryanair
3,Brussels,173 kn,Sun 5 Dec,Wed 8 Dec,Ryanair
4,Manchester,180 kn,Sun 5 Dec,Sun 5 Dec,Ryanair
5,Banja Luka,225 kn,Sun 5 Dec,Mon 6 Dec,Ryanair
6,Málaga,255 kn,Sun 5 Dec,Wed 8 Dec,Ryanair
7,Paris,278 kn,Sun 5 Dec,Wed 8 Dec,Ryanair
8,Bratislava,301 kn,Sun 5 Dec,Sun 12 Dec,Ryanair
9,Douala,10.465 kn,Sun 5 Dec,Mon 3 Jan,Ryanair + Turkish Airlines
10,Gothenburg,203 kn,Mon 6 Dec,Wed 8 Dec,Ryanair
11,Vilnius,301 kn,Mon 6 Dec,Wed 8 Dec,Ryanair
12,Malmo,76 kn,Tue 7 Dec,Tue 14 Dec,Ryanair
13,Harare,5.259 kn,Thu 9 Dec,Mon 27 Dec,KLM + Airlink
14,Dublin,278 kn,Fri 10 Dec,Tue 18 Jan,Ryanair
15,Lviv,293 kn,Fri 10 Dec,Mon 13 Dec,Ryanair + Wizz Air
16,Baden-Baden,75 kn,Sat 11 Dec,Tue 14 Dec,Ryanair
17,Thessaloniki,107 kn,Sun 12 Dec,Thu 23 Dec,Ryanair
18,Thessaloniki,218 kn,Sun 12 Dec,Sun 12 Dec,Ryanair
19,Reykjavik,549 kn,Sun 12 Dec,Wed 29 Dec,Ryanair + Wizz Air
20,Riga,210 kn,Mon 13 Dec,Wed 15 Dec,Ryanair
21,Basel,413 kn,Mon 13 Dec,Tue 14 Dec,Ryanair + Wizz Air
22,Chisinau,862 kn,Mon 13 Dec,Thu 16 Dec,Ryanair + Wizz Air
23,Milan,82 kn,Tue 14 Dec,Thu 16 Dec,Ryanair
24,St Petersburg,823 kn,Tue 14 Dec,Sat 18 Dec,Ryanair + Wizz Air
25,Bishkek,3.003 kn,Thu 16 Dec,Sun 19 Dec,Turkish Airlines
26,Eindhoven,86 kn,Fri 17 Dec,Tue 21 Dec,Ryanair
27,Paphos,127 kn,Fri 17 Dec,Mon 20 Dec,Ryanair
28,Gdansk,212 kn,Sun 19 Dec,Wed 29 Dec,Ryanair
29,Dublin,225 kn,Sun 19 Dec,Wed 5 Jan,Ryanair
30,Málaga,187 kn,Tue 21 Dec,Tue 28 Dec,Ryanair
31,Eindhoven,188 kn,Thu 23 Dec,Thu 6 Jan,Ryanair
32,Phnom Penh,5.072 kn,Fri 24 Dec,Fri 7 Jan,Turkish Airlines + Malaysia Airlines
33,Belize City,8.940 kn,Fri 24 Dec,Sat 8 Jan,Lufthansa + United
34,Entebbe,3.900 kn,Sat 25 Dec,Sat 1 Jan,Qatar Airways
35,Billund,293 kn,Thu 30 Dec,Mon 3 Jan,Ryanair
36,Moscow,1.309 kn,Fri 31 Dec,Mon 10 Jan,Nordwind Airlines
37,Podgorica,107 kn,Sat 1 Jan,Sat 8 Jan,Ryanair
38,Managua,12.573 kn,Wed 5 Jan,Thu 20 Jan,Ryanair + TACA
39,Bucharest,283 kn,Tue 11 Jan,Thu 13 Jan,Ryanair + Wizz Air
40,Oslo,180 kn,Wed 12 Jan,Wed 19 Jan,Ryanair
41,Istanbul,888 kn,Wed 12 Jan,Tue 18 Jan,Ryanair + Pegasus Airlines
42,Kyiv,1.683 kn,Wed 12 Jan,Sun 16 Jan,Windrose
43,Prague,278 kn,Thu 13 Jan,Sun 16 Jan,Ryanair
44,Abu Dhabi,1.157 kn,Thu 13 Jan,Thu 20 Jan,Ryanair + Wizz Air Abu Dhabi
45,San Salvador,6.593 kn,Thu 13 Jan,Mon 17 Jan,KLM + Avianca
46,Naples,173 kn,Fri 14 Jan,Mon 17 Jan,Ryanair
47,Budapest,270 kn,Fri 14 Jan,Mon 31 Jan,Ryanair
48,Cotonou,6.063 kn,Sat 15 Jan,Mon 31 Jan,KLM + Air France
49,Porto,316 kn,Sun 16 Jan,Mon 24 Jan,Ryanair
50,Belgrade,513 kn,Mon 17 Jan,Sat 22 Jan,Ryanair + Wizz Air
51,Tirana,541 kn,Mon 17 Jan,Fri 21 Jan,Ryanair + Wizz Air
52,Skopje,541 kn,Mon 17 Jan,Fri 21 Jan,Ryanair + Wizz Air
53,Manama,2.526 kn,Mon 17 Jan,Fri 21 Jan,Air Serbia + Pegasus Airlines
54,Guatemala City,4.617 kn,Mon 17 Jan,Mon 18 Apr,United
55,Podgorica,232 kn,Tue 18 Jan,Sat 22 Jan,Ryanair
56,Gibraltar,633 kn,Thu 20 Jan,Mon 24 Jan,Ryanair + Wizz Air UK
57,Baghdad,2.370 kn,Thu 20 Jan,Thu 27 Jan,Ryanair + Pegasus Airlines
58,Bridgetown,4.079 kn,Thu 20 Jan,Thu 27 Jan,KLM
59,Quito,5.456 kn,Thu 20 Jan,Thu 31 Mar,Croatia Airlines + United

In [411]:
print(data.shape)
#print(data.values)
print(data.loc[:, "Prices"])

(60, 5)
0        180 kn
1        211 kn
2        300 kn
3        173 kn
4        180 kn
5        225 kn
6        255 kn
7        278 kn
8        301 kn
9     10.465 kn
10       203 kn
11       301 kn
12        76 kn
13     5.259 kn
14       278 kn
15       293 kn
16        75 kn
17       107 kn
18       218 kn
19       549 kn
20       210 kn
21       413 kn
22       862 kn
23        82 kn
24       823 kn
25     3.003 kn
26        86 kn
27       127 kn
28       212 kn
29       225 kn
30       187 kn
31       188 kn
32     5.072 kn
33     8.940 kn
34     3.900 kn
35       293 kn
36     1.309 kn
37       107 kn
38    12.573 kn
39       283 kn
40       180 kn
41       888 kn
42     1.683 kn
43       278 kn
44     1.157 kn
45     6.593 kn
46       173 kn
47       270 kn
48     6.063 kn
49       316 kn
50       513 kn
51       541 kn
52       541 kn
53     2.526 kn
54     4.617 kn
55       232 kn
56       633 kn
57     2.370 kn
58     4.079 kn
59     5.456 kn
Name: Prices, dtype: object

In [412]:
spl = list()
for price in data["Prices"]:
    #razdvoji cijenu od valute
    spl.append(price.split(" "))

prices = pd.Series(
    [float(i[0].replace(".", ""))/7.52 for i in spl],
    index = [j for j in range(len(spl))]
)
data["Prices"] = prices
data["Prices"]=data["Prices"].apply(lambda x:round(x,2))


data.insert(2, "Currency", "")
data.Currency = "EUR"


data

,Destination,Prices,Currency,Departure date,Arrival date,Airline
0,Valletta,23.94,EUR,Sat 4 Dec,Sat 4 Dec,Ryanair
1,Paphos,28.06,EUR,Sat 4 Dec,Mon 6 Dec,Ryanair
2,Tallinn,39.89,EUR,Sat 4 Dec,Sun 12 Dec,Ryanair
3,Brussels,23.01,EUR,Sun 5 Dec,Wed 8 Dec,Ryanair
4,Manchester,23.94,EUR,Sun 5 Dec,Sun 5 Dec,Ryanair
5,Banja Luka,29.92,EUR,Sun 5 Dec,Mon 6 Dec,Ryanair
6,Málaga,33.91,EUR,Sun 5 Dec,Wed 8 Dec,Ryanair
7,Paris,36.97,EUR,Sun 5 Dec,Wed 8 Dec,Ryanair
8,Bratislava,40.03,EUR,Sun 5 Dec,Sun 12 Dec,Ryanair
9,Douala,1391.62,EUR,Sun 5 Dec,Mon 3 Jan,Ryanair + Turkish Airlines
10,Gothenburg,26.99,EUR,Mon 6 Dec,Wed 8 Dec,Ryanair
11,Vilnius,40.03,EUR,Mon 6 Dec,Wed 8 Dec,Ryanair
12,Malmo,10.11,EUR,Tue 7 Dec,Tue 14 Dec,Ryanair
13,Harare,699.34,EUR,Thu 9 Dec,Mon 27 Dec,KLM + Airlink
14,Dublin,36.97,EUR,Fri 10 Dec,Tue 18 Jan,Ryanair
15,Lviv,38.96,EUR,Fri 10 Dec,Mon 13 Dec,Ryanair + Wizz Air
16,Baden-Baden,9.97,EUR,Sat 11 Dec,Tue 14 Dec,Ryanair
17,Thessaloniki,14.23,EUR,Sun 12 Dec,Thu 23 Dec,Ryanair
18,Thessaloniki,28.99,EUR,Sun 12 Dec,Sun 12 Dec,Ryanair
19,Reykjavik,73.01,EUR,Sun 12 Dec,Wed 29 Dec,Ryanair + Wizz Air
20,Riga,27.93,EUR,Mon 13 Dec,Wed 15 Dec,Ryanair
21,Basel,54.92,EUR,Mon 13 Dec,Tue 14 Dec,Ryanair + Wizz Air
22,Chisinau,114.63,EUR,Mon 13 Dec,Thu 16 Dec,Ryanair + Wizz Air
23,Milan,10.90,EUR,Tue 14 Dec,Thu 16 Dec,Ryanair
24,St Petersburg,109.44,EUR,Tue 14 Dec,Sat 18 Dec,Ryanair + Wizz Air
25,Bishkek,399.34,EUR,Thu 16 Dec,Sun 19 Dec,Turkish Airlines
26,Eindhoven,11.44,EUR,Fri 17 Dec,Tue 21 Dec,Ryanair
27,Paphos,16.89,EUR,Fri 17 Dec,Mon 20 Dec,Ryanair
28,Gdansk,28.19,EUR,Sun 19 Dec,Wed 29 Dec,Ryanair
29,Dublin,29.92,EUR,Sun 19 Dec,Wed 5 Jan,Ryanair
30,Málaga,24.87,EUR,Tue 21 Dec,Tue 28 Dec,Ryanair
31,Eindhoven,25.00,EUR,Thu 23 Dec,Thu 6 Jan,Ryanair
32,Phnom Penh,674.47,EUR,Fri 24 Dec,Fri 7 Jan,Turkish Airlines + Malaysia Airlines
33,Belize City,1188.83,EUR,Fri 24 Dec,Sat 8 Jan,Lufthansa + United
34,Entebbe,518.62,EUR,Sat 25 Dec,Sat 1 Jan,Qatar Airways
35,Billund,38.96,EUR,Thu 30 Dec,Mon 3 Jan,Ryanair
36,Moscow,174.07,EUR,Fri 31 Dec,Mon 10 Jan,Nordwind Airlines
37,Podgorica,14.23,EUR,Sat 1 Jan,Sat 8 Jan,Ryanair
38,Managua,1671.94,EUR,Wed 5 Jan,Thu 20 Jan,Ryanair + TACA
39,Bucharest,37.63,EUR,Tue 11 Jan,Thu 13 Jan,Ryanair + Wizz Air
40,Oslo,23.94,EUR,Wed 12 Jan,Wed 19 Jan,Ryanair
41,Istanbul,118.09,EUR,Wed 12 Jan,Tue 18 Jan,Ryanair + Pegasus Airlines
42,Kyiv,223.80,EUR,Wed 12 Jan,Sun 16 Jan,Windrose
43,Prague,36.97,EUR,Thu 13 Jan,Sun 16 Jan,Ryanair
44,Abu Dhabi,153.86,EUR,Thu 13 Jan,Thu 20 Jan,Ryanair + Wizz Air Abu Dhabi
45,San Salvador,876.73,EUR,Thu 13 Jan,Mon 17 Jan,KLM + Avianca
46,Naples,23.01,EUR,Fri 14 Jan,Mon 17 Jan,Ryanair
47,Budapest,35.90,EUR,Fri 14 Jan,Mon 31 Jan,Ryanair
48,Cotonou,806.25,EUR,Sat 15 Jan,Mon 31 Jan,KLM + Air France
49,Porto,42.02,EUR,Sun 16 Jan,Mon 24 Jan,Ryanair
50,Belgrade,68.22,EUR,Mon 17 Jan,Sat 22 Jan,Ryanair + Wizz Air
51,Tirana,71.94,EUR,Mon 17 Jan,Fri 21 Jan,Ryanair + Wizz Air
52,Skopje,71.94,EUR,Mon 17 Jan,Fri 21 Jan,Ryanair + Wizz Air
53,Manama,335.90,EUR,Mon 17 Jan,Fri 21 Jan,Air Serbia + Pegasus Airlines
54,Guatemala City,613.96,EUR,Mon 17 Jan,Mon 18 Apr,United
55,Podgorica,30.85,EUR,Tue 18 Jan,Sat 22 Jan,Ryanair
56,Gibraltar,84.18,EUR,Thu 20 Jan,Mon 24 Jan,Ryanair + Wizz Air UK
57,Baghdad,315.16,EUR,Thu 20 Jan,Thu 27 Jan,Ryanair + Pegasus Airlines
58,Bridgetown,542.42,EUR,Thu 20 Jan,Thu 27 Jan,KLM
59,Quito,725.53,EUR,Thu 20 Jan,Thu 31 Mar,Croatia Airlines + United

In [413]:
#micanje dana iz datuma
data["Day"] = [i[0:4].strip() for i in data["Departure date"]]
departure = [i[4:len(i)+1] for i in data["Departure date"]]
data["Departure date"] = departure
arrival = [i[4:len(i)+1] for i in data["Arrival date"]]
data["Arrival date"] = arrival
data

,Destination,Prices,Currency,Departure date,Arrival date,Airline,Day
0,Valletta,23.94,EUR,4 Dec,4 Dec,Ryanair,Sat
1,Paphos,28.06,EUR,4 Dec,6 Dec,Ryanair,Sat
2,Tallinn,39.89,EUR,4 Dec,12 Dec,Ryanair,Sat
3,Brussels,23.01,EUR,5 Dec,8 Dec,Ryanair,Sun
4,Manchester,23.94,EUR,5 Dec,5 Dec,Ryanair,Sun
5,Banja Luka,29.92,EUR,5 Dec,6 Dec,Ryanair,Sun
6,Málaga,33.91,EUR,5 Dec,8 Dec,Ryanair,Sun
7,Paris,36.97,EUR,5 Dec,8 Dec,Ryanair,Sun
8,Bratislava,40.03,EUR,5 Dec,12 Dec,Ryanair,Sun
9,Douala,1391.62,EUR,5 Dec,3 Jan,Ryanair + Turkish Airlines,Sun
10,Gothenburg,26.99,EUR,6 Dec,8 Dec,Ryanair,Mon
11,Vilnius,40.03,EUR,6 Dec,8 Dec,Ryanair,Mon
12,Malmo,10.11,EUR,7 Dec,14 Dec,Ryanair,Tue
13,Harare,699.34,EUR,9 Dec,27 Dec,KLM + Airlink,Thu
14,Dublin,36.97,EUR,10 Dec,18 Jan,Ryanair,Fri
15,Lviv,38.96,EUR,10 Dec,13 Dec,Ryanair + Wizz Air,Fri
16,Baden-Baden,9.97,EUR,11 Dec,14 Dec,Ryanair,Sat
17,Thessaloniki,14.23,EUR,12 Dec,23 Dec,Ryanair,Sun
18,Thessaloniki,28.99,EUR,12 Dec,12 Dec,Ryanair,Sun
19,Reykjavik,73.01,EUR,12 Dec,29 Dec,Ryanair + Wizz Air,Sun
20,Riga,27.93,EUR,13 Dec,15 Dec,Ryanair,Mon
21,Basel,54.92,EUR,13 Dec,14 Dec,Ryanair + Wizz Air,Mon
22,Chisinau,114.63,EUR,13 Dec,16 Dec,Ryanair + Wizz Air,Mon
23,Milan,10.90,EUR,14 Dec,16 Dec,Ryanair,Tue
24,St Petersburg,109.44,EUR,14 Dec,18 Dec,Ryanair + Wizz Air,Tue
25,Bishkek,399.34,EUR,16 Dec,19 Dec,Turkish Airlines,Thu
26,Eindhoven,11.44,EUR,17 Dec,21 Dec,Ryanair,Fri
27,Paphos,16.89,EUR,17 Dec,20 Dec,Ryanair,Fri
28,Gdansk,28.19,EUR,19 Dec,29 Dec,Ryanair,Sun
29,Dublin,29.92,EUR,19 Dec,5 Jan,Ryanair,Sun
30,Málaga,24.87,EUR,21 Dec,28 Dec,Ryanair,Tue
31,Eindhoven,25.00,EUR,23 Dec,6 Jan,Ryanair,Thu
32,Phnom Penh,674.47,EUR,24 Dec,7 Jan,Turkish Airlines + Malaysia Airlines,Fri
33,Belize City,1188.83,EUR,24 Dec,8 Jan,Lufthansa + United,Fri
34,Entebbe,518.62,EUR,25 Dec,1 Jan,Qatar Airways,Sat
35,Billund,38.96,EUR,30 Dec,3 Jan,Ryanair,Thu
36,Moscow,174.07,EUR,31 Dec,10 Jan,Nordwind Airlines,Fri
37,Podgorica,14.23,EUR,1 Jan,8 Jan,Ryanair,Sat
38,Managua,1671.94,EUR,5 Jan,20 Jan,Ryanair + TACA,Wed
39,Bucharest,37.63,EUR,11 Jan,13 Jan,Ryanair + Wizz Air,Tue
40,Oslo,23.94,EUR,12 Jan,19 Jan,Ryanair,Wed
41,Istanbul,118.09,EUR,12 Jan,18 Jan,Ryanair + Pegasus Airlines,Wed
42,Kyiv,223.80,EUR,12 Jan,16 Jan,Windrose,Wed
43,Prague,36.97,EUR,13 Jan,16 Jan,Ryanair,Thu
44,Abu Dhabi,153.86,EUR,13 Jan,20 Jan,Ryanair + Wizz Air Abu Dhabi,Thu
45,San Salvador,876.73,EUR,13 Jan,17 Jan,KLM + Avianca,Thu
46,Naples,23.01,EUR,14 Jan,17 Jan,Ryanair,Fri
47,Budapest,35.90,EUR,14 Jan,31 Jan,Ryanair,Fri
48,Cotonou,806.25,EUR,15 Jan,31 Jan,KLM + Air France,Sat
49,Porto,42.02,EUR,16 Jan,24 Jan,Ryanair,Sun
50,Belgrade,68.22,EUR,17 Jan,22 Jan,Ryanair + Wizz Air,Mon
51,Tirana,71.94,EUR,17 Jan,21 Jan,Ryanair + Wizz Air,Mon
52,Skopje,71.94,EUR,17 Jan,21 Jan,Ryanair + Wizz Air,Mon
53,Manama,335.90,EUR,17 Jan,21 Jan,Air Serbia + Pegasus Airlines,Mon
54,Guatemala City,613.96,EUR,17 Jan,18 Apr,United,Mon
55,Podgorica,30.85,EUR,18 Jan,22 Jan,Ryanair,Tue
56,Gibraltar,84.18,EUR,20 Jan,24 Jan,Ryanair + Wizz Air UK,Thu
57,Baghdad,315.16,EUR,20 Jan,27 Jan,Ryanair + Pegasus Airlines,Thu
58,Bridgetown,542.42,EUR,20 Jan,27 Jan,KLM,Thu
59,Quito,725.53,EUR,20 Jan,31 Mar,Croatia Airlines + United,Thu

In [414]:
#u datetime format
str_month = {"Jan" : 1, "Feb" : 2, "Mar" : 3, "Apr" : 4, "May" : 5, "Jun" : 6, "Jul" : 7, "Aug" : 8, "Sep" : 9, "Oct" : 10, "Nov" : 11, "Dec" : 12}

for index, val in data["Departure date"].items():
    spl = val.split(" ")
    data["Departure date"][index] = spl[0] + "/" + str(str_month[spl[1]]) + "/2021"

for index, val in data["Arrival date"].items():
    spl = val.split(" ")
    data["Arrival date"][index] = spl[0] + "/" + str(str_month[spl[1]]) + "/2021"

data['Arrival date'] = pd.to_datetime(data['Arrival date'], format="%d/%m/%Y")
data['Departure date'] = pd.to_datetime(data['Departure date'], format="%d/%m/%Y")

data

C:\Users\Korisnik\AppData\Local\Temp/ipykernel_11040/4186104025.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Departure date"][index] = spl[0] + "/" + str(str_month[spl[1]]) + "/2021"
C:\Users\Korisnik\AppData\Local\Temp/ipykernel_11040/4186104025.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Arrival date"][index] = spl[0] + "/" + str(str_month[spl[1]]) + "/2021"

,Destination,Prices,Currency,Departure date,Arrival date,Airline,Day
0,Valletta,23.94,EUR,2021-12-04,2021-12-04,Ryanair,Sat
1,Paphos,28.06,EUR,2021-12-04,2021-12-06,Ryanair,Sat
2,Tallinn,39.89,EUR,2021-12-04,2021-12-12,Ryanair,Sat
3,Brussels,23.01,EUR,2021-12-05,2021-12-08,Ryanair,Sun
4,Manchester,23.94,EUR,2021-12-05,2021-12-05,Ryanair,Sun
5,Banja Luka,29.92,EUR,2021-12-05,2021-12-06,Ryanair,Sun
6,Málaga,33.91,EUR,2021-12-05,2021-12-08,Ryanair,Sun
7,Paris,36.97,EUR,2021-12-05,2021-12-08,Ryanair,Sun
8,Bratislava,40.03,EUR,2021-12-05,2021-12-12,Ryanair,Sun
9,Douala,1391.62,EUR,2021-12-05,2021-01-03,Ryanair + Turkish Airlines,Sun
10,Gothenburg,26.99,EUR,2021-12-06,2021-12-08,Ryanair,Mon
11,Vilnius,40.03,EUR,2021-12-06,2021-12-08,Ryanair,Mon
12,Malmo,10.11,EUR,2021-12-07,2021-12-14,Ryanair,Tue
13,Harare,699.34,EUR,2021-12-09,2021-12-27,KLM + Airlink,Thu
14,Dublin,36.97,EUR,2021-12-10,2021-01-18,Ryanair,Fri
15,Lviv,38.96,EUR,2021-12-10,2021-12-13,Ryanair + Wizz Air,Fri
16,Baden-Baden,9.97,EUR,2021-12-11,2021-12-14,Ryanair,Sat
17,Thessaloniki,14.23,EUR,2021-12-12,2021-12-23,Ryanair,Sun
18,Thessaloniki,28.99,EUR,2021-12-12,2021-12-12,Ryanair,Sun
19,Reykjavik,73.01,EUR,2021-12-12,2021-12-29,Ryanair + Wizz Air,Sun
20,Riga,27.93,EUR,2021-12-13,2021-12-15,Ryanair,Mon
21,Basel,54.92,EUR,2021-12-13,2021-12-14,Ryanair + Wizz Air,Mon
22,Chisinau,114.63,EUR,2021-12-13,2021-12-16,Ryanair + Wizz Air,Mon
23,Milan,10.90,EUR,2021-12-14,2021-12-16,Ryanair,Tue
24,St Petersburg,109.44,EUR,2021-12-14,2021-12-18,Ryanair + Wizz Air,Tue
25,Bishkek,399.34,EUR,2021-12-16,2021-12-19,Turkish Airlines,Thu
26,Eindhoven,11.44,EUR,2021-12-17,2021-12-21,Ryanair,Fri
27,Paphos,16.89,EUR,2021-12-17,2021-12-20,Ryanair,Fri
28,Gdansk,28.19,EUR,2021-12-19,2021-12-29,Ryanair,Sun
29,Dublin,29.92,EUR,2021-12-19,2021-01-05,Ryanair,Sun
30,Málaga,24.87,EUR,2021-12-21,2021-12-28,Ryanair,Tue
31,Eindhoven,25.00,EUR,2021-12-23,2021-01-06,Ryanair,Thu
32,Phnom Penh,674.47,EUR,2021-12-24,2021-01-07,Turkish Airlines + Malaysia Airlines,Fri
33,Belize City,1188.83,EUR,2021-12-24,2021-01-08,Lufthansa + United,Fri
34,Entebbe,518.62,EUR,2021-12-25,2021-01-01,Qatar Airways,Sat
35,Billund,38.96,EUR,2021-12-30,2021-01-03,Ryanair,Thu
36,Moscow,174.07,EUR,2021-12-31,2021-01-10,Nordwind Airlines,Fri
37,Podgorica,14.23,EUR,2021-01-01,2021-01-08,Ryanair,Sat
38,Managua,1671.94,EUR,2021-01-05,2021-01-20,Ryanair + TACA,Wed
39,Bucharest,37.63,EUR,2021-01-11,2021-01-13,Ryanair + Wizz Air,Tue
40,Oslo,23.94,EUR,2021-01-12,2021-01-19,Ryanair,Wed
41,Istanbul,118.09,EUR,2021-01-12,2021-01-18,Ryanair + Pegasus Airlines,Wed
42,Kyiv,223.80,EUR,2021-01-12,2021-01-16,Windrose,Wed
43,Prague,36.97,EUR,2021-01-13,2021-01-16,Ryanair,Thu
44,Abu Dhabi,153.86,EUR,2021-01-13,2021-01-20,Ryanair + Wizz Air Abu Dhabi,Thu
45,San Salvador,876.73,EUR,2021-01-13,2021-01-17,KLM + Avianca,Thu
46,Naples,23.01,EUR,2021-01-14,2021-01-17,Ryanair,Fri
47,Budapest,35.90,EUR,2021-01-14,2021-01-31,Ryanair,Fri
48,Cotonou,806.25,EUR,2021-01-15,2021-01-31,KLM + Air France,Sat
49,Porto,42.02,EUR,2021-01-16,2021-01-24,Ryanair,Sun
50,Belgrade,68.22,EUR,2021-01-17,2021-01-22,Ryanair + Wizz Air,Mon
51,Tirana,71.94,EUR,2021-01-17,2021-01-21,Ryanair + Wizz Air,Mon
52,Skopje,71.94,EUR,2021-01-17,2021-01-21,Ryanair + Wizz Air,Mon
53,Manama,335.90,EUR,2021-01-17,2021-01-21,Air Serbia + Pegasus Airlines,Mon
54,Guatemala City,613.96,EUR,2021-01-17,2021-04-18,United,Mon
55,Podgorica,30.85,EUR,2021-01-18,2021-01-22,Ryanair,Tue
56,Gibraltar,84.18,EUR,2021-01-20,2021-01-24,Ryanair + Wizz Air UK,Thu
57,Baghdad,315.16,EUR,2021-01-20,2021-01-27,Ryanair + Pegasus Airlines,Thu
58,Bridgetown,542.42,EUR,2021-01-20,2021-01-27,KLM,Thu
59,Quito,725.53,EUR,2021-01-20,2021-03-31,Croatia Airlines + United,Thu

In [415]:
#dodavanje vremena putovanja


for index, row in data.iterrows():
    if row["Arrival date"] < row["Departure date"]:
        data["Arrival date"][index] += pd.offsets.DateOffset(years=1)

data['Travel time'] = (data['Arrival date'] - data['Departure date']).dt.days

for index, travel in data["Travel time"].items():
    data["Travel time"][index] *=24
    if travel == 0:
        data["Travel time"][index] = 1
data

C:\Users\Korisnik\AppData\Local\Temp/ipykernel_11040/3234857152.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Arrival date"][index] += pd.offsets.DateOffset(years=1)
C:\Users\Korisnik\AppData\Local\Temp/ipykernel_11040/3234857152.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Travel time"][index] *=24
C:\Users\Korisnik\AppData\Local\Temp/ipykernel_11040/3234857152.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Travel time"][index] = 1

,Destination,Prices,Currency,Departure date,Arrival date,Airline,Day,Travel time
0,Valletta,23.94,EUR,2021-12-04,2021-12-04,Ryanair,Sat,1
1,Paphos,28.06,EUR,2021-12-04,2021-12-06,Ryanair,Sat,48
2,Tallinn,39.89,EUR,2021-12-04,2021-12-12,Ryanair,Sat,192
3,Brussels,23.01,EUR,2021-12-05,2021-12-08,Ryanair,Sun,72
4,Manchester,23.94,EUR,2021-12-05,2021-12-05,Ryanair,Sun,1
5,Banja Luka,29.92,EUR,2021-12-05,2021-12-06,Ryanair,Sun,24
6,Málaga,33.91,EUR,2021-12-05,2021-12-08,Ryanair,Sun,72
7,Paris,36.97,EUR,2021-12-05,2021-12-08,Ryanair,Sun,72
8,Bratislava,40.03,EUR,2021-12-05,2021-12-12,Ryanair,Sun,168
9,Douala,1391.62,EUR,2021-12-05,2022-01-03,Ryanair + Turkish Airlines,Sun,696
10,Gothenburg,26.99,EUR,2021-12-06,2021-12-08,Ryanair,Mon,48
11,Vilnius,40.03,EUR,2021-12-06,2021-12-08,Ryanair,Mon,48
12,Malmo,10.11,EUR,2021-12-07,2021-12-14,Ryanair,Tue,168
13,Harare,699.34,EUR,2021-12-09,2021-12-27,KLM + Airlink,Thu,432
14,Dublin,36.97,EUR,2021-12-10,2022-01-18,Ryanair,Fri,936
15,Lviv,38.96,EUR,2021-12-10,2021-12-13,Ryanair + Wizz Air,Fri,72
16,Baden-Baden,9.97,EUR,2021-12-11,2021-12-14,Ryanair,Sat,72
17,Thessaloniki,14.23,EUR,2021-12-12,2021-12-23,Ryanair,Sun,264
18,Thessaloniki,28.99,EUR,2021-12-12,2021-12-12,Ryanair,Sun,1
19,Reykjavik,73.01,EUR,2021-12-12,2021-12-29,Ryanair + Wizz Air,Sun,408
20,Riga,27.93,EUR,2021-12-13,2021-12-15,Ryanair,Mon,48
21,Basel,54.92,EUR,2021-12-13,2021-12-14,Ryanair + Wizz Air,Mon,24
22,Chisinau,114.63,EUR,2021-12-13,2021-12-16,Ryanair + Wizz Air,Mon,72
23,Milan,10.90,EUR,2021-12-14,2021-12-16,Ryanair,Tue,48
24,St Petersburg,109.44,EUR,2021-12-14,2021-12-18,Ryanair + Wizz Air,Tue,96
25,Bishkek,399.34,EUR,2021-12-16,2021-12-19,Turkish Airlines,Thu,72
26,Eindhoven,11.44,EUR,2021-12-17,2021-12-21,Ryanair,Fri,96
27,Paphos,16.89,EUR,2021-12-17,2021-12-20,Ryanair,Fri,72
28,Gdansk,28.19,EUR,2021-12-19,2021-12-29,Ryanair,Sun,240
29,Dublin,29.92,EUR,2021-12-19,2022-01-05,Ryanair,Sun,408
30,Málaga,24.87,EUR,2021-12-21,2021-12-28,Ryanair,Tue,168
31,Eindhoven,25.00,EUR,2021-12-23,2022-01-06,Ryanair,Thu,336
32,Phnom Penh,674.47,EUR,2021-12-24,2022-01-07,Turkish Airlines + Malaysia Airlines,Fri,336
33,Belize City,1188.83,EUR,2021-12-24,2022-01-08,Lufthansa + United,Fri,360
34,Entebbe,518.62,EUR,2021-12-25,2022-01-01,Qatar Airways,Sat,168
35,Billund,38.96,EUR,2021-12-30,2022-01-03,Ryanair,Thu,96
36,Moscow,174.07,EUR,2021-12-31,2022-01-10,Nordwind Airlines,Fri,240
37,Podgorica,14.23,EUR,2021-01-01,2021-01-08,Ryanair,Sat,168
38,Managua,1671.94,EUR,2021-01-05,2021-01-20,Ryanair + TACA,Wed,360
39,Bucharest,37.63,EUR,2021-01-11,2021-01-13,Ryanair + Wizz Air,Tue,48
40,Oslo,23.94,EUR,2021-01-12,2021-01-19,Ryanair,Wed,168
41,Istanbul,118.09,EUR,2021-01-12,2021-01-18,Ryanair + Pegasus Airlines,Wed,144
42,Kyiv,223.80,EUR,2021-01-12,2021-01-16,Windrose,Wed,96
43,Prague,36.97,EUR,2021-01-13,2021-01-16,Ryanair,Thu,72
44,Abu Dhabi,153.86,EUR,2021-01-13,2021-01-20,Ryanair + Wizz Air Abu Dhabi,Thu,168
45,San Salvador,876.73,EUR,2021-01-13,2021-01-17,KLM + Avianca,Thu,96
46,Naples,23.01,EUR,2021-01-14,2021-01-17,Ryanair,Fri,72
47,Budapest,35.90,EUR,2021-01-14,2021-01-31,Ryanair,Fri,408
48,Cotonou,806.25,EUR,2021-01-15,2021-01-31,KLM + Air France,Sat,384
49,Porto,42.02,EUR,2021-01-16,2021-01-24,Ryanair,Sun,192
50,Belgrade,68.22,EUR,2021-01-17,2021-01-22,Ryanair + Wizz Air,Mon,120
51,Tirana,71.94,EUR,2021-01-17,2021-01-21,Ryanair + Wizz Air,Mon,96
52,Skopje,71.94,EUR,2021-01-17,2021-01-21,Ryanair + Wizz Air,Mon,96
53,Manama,335.90,EUR,2021-01-17,2021-01-21,Air Serbia + Pegasus Airlines,Mon,96
54,Guatemala City,613.96,EUR,2021-01-17,2021-04-18,United,Mon,2184
55,Podgorica,30.85,EUR,2021-01-18,2021-01-22,Ryanair,Tue,96
56,Gibraltar,84.18,EUR,2021-01-20,2021-01-24,Ryanair + Wizz Air UK,Thu,96
57,Baghdad,315.16,EUR,2021-01-20,2021-01-27,Ryanair + Pegasus Airlines,Thu,168
58,Bridgetown,542.42,EUR,2021-01-20,2021-01-27,KLM,Thu,168
59,Quito,725.53,EUR,2021-01-20,2021-03-31,Croatia Airlines + United,Thu,1680

In [418]:

data.loc[data.Day == "Wed"].sort_values("Prices", ascending = True).head(1)

,Destination,Prices,Currency,Departure date,Arrival date,Airline,Day,Travel time
40,Oslo,23.94,EUR,2021-01-12,2021-01-19,Ryanair,Wed,168